name: Docker Image CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    name: Crear Docker
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Login en Docker Hub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Descargo este repositorio git
        uses: actions/checkout@v2
    
      - name: Creacion de imagen Docker y publicacion en Docker Hub
        id: docker_build
        uses:  docker/build-push-action@v2
        with: 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qemu_stm32:latest
        
